### ISSUE TITLE
💡[Feature]: adding Expense Tracker App

### ISSUE THREAD

**Issue by itznayan** [smilewithkhushi/BasicNative#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Expense tracker application for showing expense

### Use Case

user will able to track his expense.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by itznayan** [comment]
@smilewithkhushi please provide labels.
